// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVlGA_haJ1J94W9CUIrt3xB7EcPi3HJqc',
    appId: '1:220210285911:android:baf6399578774969dd4212',
    messagingSenderId: '220210285911',
    projectId: 'cadeli-app',
    storageBucket: 'cadeli-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz2CJcBVeMbAyX1tLmfEBj_Y2QEJmDXV8',
    appId: '1:220210285911:ios:d525d1c977d78f8ddd4212',
    messagingSenderId: '220210285911',
    projectId: 'cadeli-app',
    storageBucket: 'cadeli-app.firebasestorage.app',
    androidClientId: '220210285911-0qidcl3rcopqf728ve7la0umuupn46fc.apps.googleusercontent.com',
    iosClientId: '220210285911-31af5jjv39qv6p9f745j1rnci70md9rf.apps.googleusercontent.com',
    iosBundleId: 'com.cadeli.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBChZi1Sy1M5NXqfdjp7boq42u3Uwhn6-U',
    appId: '1:220210285911:web:6b3aee3559c1538fdd4212',
    messagingSenderId: '220210285911',
    projectId: 'cadeli-app',
    authDomain: 'cadeli-app.firebaseapp.com',
    storageBucket: 'cadeli-app.firebasestorage.app',
    measurementId: 'G-N773WZCSGP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz2CJcBVeMbAyX1tLmfEBj_Y2QEJmDXV8',
    appId: '1:220210285911:ios:d525d1c977d78f8ddd4212',
    messagingSenderId: '220210285911',
    projectId: 'cadeli-app',
    storageBucket: 'cadeli-app.firebasestorage.app',
    androidClientId: '220210285911-0qidcl3rcopqf728ve7la0umuupn46fc.apps.googleusercontent.com',
    iosClientId: '220210285911-31af5jjv39qv6p9f745j1rnci70md9rf.apps.googleusercontent.com',
    iosBundleId: 'com.cadeli.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBChZi1Sy1M5NXqfdjp7boq42u3Uwhn6-U',
    appId: '1:220210285911:web:3170dd37806a661bdd4212',
    messagingSenderId: '220210285911',
    projectId: 'cadeli-app',
    authDomain: 'cadeli-app.firebaseapp.com',
    storageBucket: 'cadeli-app.firebasestorage.app',
    measurementId: 'G-BRCEGJRY70',
  );

}